package com.hc.repositories;

import com.hc.model.AdmSideLevelCode;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 02/07/2022
*/
@Repository
public interface AdmSideLevelCodeRepository extends JpaRepository<AdmSideLevelCode, Long>, JpaSpecificationExecutor<AdmSideLevelCode>, QuerydslPredicateExecutor<AdmSideLevelCode> {

}
