package com.hc.repositories;

import com.hc.model.EmsExpert;
import com.mysql.cj.jdbc.Clob;

import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Spring Data Generator on 01/01/2022
*/
@Repository
public interface EmsExpertRepository extends JpaRepository<EmsExpert, Long>, JpaSpecificationExecutor<EmsExpert>, QuerydslPredicateExecutor<EmsExpert> {

	@Transactional
	@Modifying(clearAutomatically = true)
	@Query(value="update ems_expert set RECENT_PHOTO_FILE=:P_NEW_IMAGE where EXPERT_ID =:P_EXPERT_ID", nativeQuery = true)
	public void UpdateExpertImage(@Param("P_NEW_IMAGE") byte[] P_NEW_IMAGE,@Param("P_EXPERT_ID") Long P_EXPERT_ID);
}
