package com.hc.repositories;

import com.hc.model.EmsExpert;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 01/01/2022
*/
@Repository
public interface EmsExpertRepository extends JpaRepository<EmsExpert, Long>, JpaSpecificationExecutor<EmsExpert>, QuerydslPredicateExecutor<EmsExpert> {

}
