package com.hc.repositories;

import com.hc.model.EmsFinancialRequest;

import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Spring Data Generator on 01/01/2022
*/
@Repository
public interface EmsFinancialRequestRepository extends JpaRepository<EmsFinancialRequest, Long>, JpaSpecificationExecutor<EmsFinancialRequest>, QuerydslPredicateExecutor<EmsFinancialRequest> {
	@Transactional
	@Modifying(clearAutomatically = true)
	@Query("update EmsFinancialRequest finReq set finReq.shakwaText =:ShakwaText,finReq.shakwaDate=sysdate where finReq.requestId =:ID")
	public void AddShakwa(Long ID,String ShakwaText);
	@Transactional
	@Modifying(clearAutomatically = true)
	@Query(value = "CALL ADD_NEW_FINANCIAL_REQ(:P_EXPERT_ID,:P_HOUR_PRICE)", nativeQuery = true)
	 public void AddFinancialRequest(@Param("P_HOUR_PRICE") BigDecimal P_HOUR_PRICE,@Param("P_EXPERT_ID") Long P_EXPERT_ID);

}
