package com.hc.repositories;

import com.hc.model.EmsFinancialRequestDtl;
import com.hc.model.EmsFinancialRequestDtlPK;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 01/01/2022
*/
@Repository
public interface EmsFinancialRequestDtlRepository extends JpaRepository<EmsFinancialRequestDtl, EmsFinancialRequestDtlPK>, JpaSpecificationExecutor<EmsFinancialRequestDtl>, QuerydslPredicateExecutor<EmsFinancialRequestDtl> {

}
