package com.hc.repositories;

import com.hc.model.EmsProjectExpert;
import com.hc.model.EmsProjectExpertPK;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 01/01/2022
*/
@Repository
public interface EmsProjectExpertRepository extends JpaRepository<EmsProjectExpert, EmsProjectExpertPK>, JpaSpecificationExecutor<EmsProjectExpert>, QuerydslPredicateExecutor<EmsProjectExpert> {

}
