package com.hc.repositories;

import com.hc.model.PrtsProjectEngineeringStudy;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Repository
public interface PrtsProjectEngineeringStudyRepository extends JpaRepository<PrtsProjectEngineeringStudy, Long>, JpaSpecificationExecutor<PrtsProjectEngineeringStudy>, QuerydslPredicateExecutor<PrtsProjectEngineeringStudy> {

}
