package com.hc.repositories;

import com.hc.model.PrtsLookupMainCode;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 02/07/2022
*/
@Repository
public interface PrtsLookupMainCodeRepository extends JpaRepository<PrtsLookupMainCode, Long>, JpaSpecificationExecutor<PrtsLookupMainCode>, QuerydslPredicateExecutor<PrtsLookupMainCode> {

	@Query(value="select * from PRTS_LOOKUP_MAIN_CODE where LOOKUP_TYPE =:lookupId", nativeQuery = true)
	public List<PrtsLookupMainCode> getallLookupsValue(Long lookupId);
	@Query(value="select * from PRTS_LOOKUP_MAIN_CODE where LOOKUP_TYPE =:lookupId and LOOKUP_ID_PARENT=:parentlookup", nativeQuery = true)
	public List<PrtsLookupMainCode> getallLookupsValueAndDepend(Long lookupId,Long parentlookup);
}
