package com.hc.repositories;

import com.hc.model.PrtsProjectItem;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 02/07/2022
*/
@Repository
public interface PrtsProjectItemRepository extends JpaRepository<PrtsProjectItem, Long>, JpaSpecificationExecutor<PrtsProjectItem>, QuerydslPredicateExecutor<PrtsProjectItem> {
	
	List<PrtsProjectItem>findByprojectId(Long projectId);
	
	@Procedure(value = "VALIDATE_PROJECT_ITEMS",outputParameterName = "P_STATUS")
	String ValidateProjectItems( @Param(value = "P_PROJECT_ID") Integer P_PROJECT_ID, @Param(value = "P_NEW_TOTAL_AMOUNT") Integer P_NEW_TOTAL_AMOUNT, @Param(value = "P_NEW_TOTAL_PERCENTAGE") Integer P_NEW_TOTAL_PERCENTAGE);

	

}
