package com.hc.managers;

import com.hc.model.AdmSideCode;
import com.hc.repositories.AdmSideCodeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 02/07/2022
*/
@Component
public class AdmSideCodeService {

	private AdmSideCodeRepository admSideCodeRepository;

	@Autowired
	public AdmSideCodeService(AdmSideCodeRepository admSideCodeRepository) {
		this.admSideCodeRepository = admSideCodeRepository;
	}

}
