package com.hc.managers;

import com.hc.model.AdmSideLevelCode;
import com.hc.repositories.AdmSideLevelCodeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 02/07/2022
*/
@Component
public class AdmSideLevelCodeService {

	private AdmSideLevelCodeRepository admSideLevelCodeRepository;

	@Autowired
	public AdmSideLevelCodeService(AdmSideLevelCodeRepository admSideLevelCodeRepository) {
		this.admSideLevelCodeRepository = admSideLevelCodeRepository;
	}

}
