package com.hc.managers;

import com.hc.model.EmsCountryCode;
import com.hc.model.EmsExpert;
import com.hc.repositories.EmsExpertRepository;
import com.hc.security.administration.UserRepo;
import com.hc.security.administration.UserService;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

/**
* Generated by Spring Data Generator on 01/01/2022
*/
@Service
@RequiredArgsConstructor
@Slf4j
public class EmsExpertService {

	private EmsExpertRepository emsExpertRepository;

	@Autowired
	public EmsExpertService(EmsExpertRepository emsExpertRepository) {
		this.emsExpertRepository = emsExpertRepository;
	}

	public EmsExpert getExpert(Long Id){
		return emsExpertRepository.getById(Id);
	   } 
}
