package com.hc.managers;

import com.hc.model.EmsJobCode;
import com.hc.model.EmsStudyFieldCode;
import com.hc.repositories.EmsJobCodeRepository;
import com.hc.security.administration.UserRepo;
import com.hc.security.administration.UserService;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

/**
* Generated by Spring Data Generator on 01/01/2022
*/
@Service
@RequiredArgsConstructor
@Slf4j
public class EmsJobCodeService {

	private EmsJobCodeRepository emsJobCodeRepository;

	@Autowired
	public EmsJobCodeService(EmsJobCodeRepository emsJobCodeRepository) {
		this.emsJobCodeRepository = emsJobCodeRepository;
	}
	public List<EmsJobCode> getall(){
		return emsJobCodeRepository.findAll();
	}


}
