package com.hc.managers;

import com.hc.model.EmsTask;
import com.hc.repositories.EmsTaskRepository;
import com.hc.security.administration.UserRepo;
import com.hc.security.administration.UserService;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

/**
* Generated by Spring Data Generator on 01/01/2022
*/
@Service
@RequiredArgsConstructor
@Slf4j
public class EmsTaskService {

	private EmsTaskRepository emsTaskRepository;

	@Autowired
	public EmsTaskService(EmsTaskRepository emsTaskRepository) {
		this.emsTaskRepository = emsTaskRepository;
	}

}
