package com.hc.managers;

import com.hc.model.PrtsProjectTiming;
import com.hc.repositories.PrtsProjectTimingRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectTimingService {

	private PrtsProjectTimingRepository prtsProjectTimingRepository;

	@Autowired
	public PrtsProjectTimingService(PrtsProjectTimingRepository prtsProjectTimingRepository) {
		this.prtsProjectTimingRepository = prtsProjectTimingRepository;
	}

}
