package com.hc.managers;

import com.hc.model.PrtsLookupMainCode;
import com.hc.repositories.PrtsLookupMainCodeRepository;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 02/07/2022
*/
@Component
public class PrtsLookupMainCodeService {

	private PrtsLookupMainCodeRepository prtsLookupMainCodeRepository;

	@Autowired
	public PrtsLookupMainCodeService(PrtsLookupMainCodeRepository prtsLookupMainCodeRepository) {
		this.prtsLookupMainCodeRepository = prtsLookupMainCodeRepository;
	}

	public List<PrtsLookupMainCode> getallDepend(Long lookupType, Long lookupDependCode) {
		// TODO Auto-generated method stub
		return prtsLookupMainCodeRepository.getallLookupsValueAndDepend(lookupType, lookupDependCode);
	}

	public List<PrtsLookupMainCode> getall(Long lookupType) {
		// TODO Auto-generated method stub
		return prtsLookupMainCodeRepository.getallLookupsValue(lookupType);
	}
	public PrtsLookupMainCode SaveLookup( PrtsLookupMainCode prtsLookupMainCode) {
		// TODO Auto-generated method stub
		return prtsLookupMainCodeRepository.save(prtsLookupMainCode);
	}
	
	public void deleteLookup(Long Lookupid) {
		// TODO Auto-generated method stub
		 prtsLookupMainCodeRepository.deleteById(Lookupid);
	}
	
}
