package com.hc.managers;

import com.hc.model.PrtsProjectStatus;
import com.hc.repositories.PrtsProjectStatusRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectStatusService {

	private PrtsProjectStatusRepository prtsProjectStatusRepository;

	@Autowired
	public PrtsProjectStatusService(PrtsProjectStatusRepository prtsProjectStatusRepository) {
		this.prtsProjectStatusRepository = prtsProjectStatusRepository;
	}

}
