package com.hc.managers;

import com.hc.model.PrtsProjectNote;
import com.hc.repositories.PrtsProjectNoteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectNoteService {

	private PrtsProjectNoteRepository prtsProjectNoteRepository;

	@Autowired
	public PrtsProjectNoteService(PrtsProjectNoteRepository prtsProjectNoteRepository) {
		this.prtsProjectNoteRepository = prtsProjectNoteRepository;
	}

}
