package com.hc.managers;

import com.hc.model.PrtsProject;
import com.hc.repositories.PrtsProjectRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectService {

	private PrtsProjectRepository prtsProjectRepository;

	@Autowired
	public PrtsProjectService(PrtsProjectRepository prtsProjectRepository) {
		this.prtsProjectRepository = prtsProjectRepository;
	}

}
