package com.hc.managers;

import com.hc.model.PrtsUserRole;
import com.hc.repositories.PrtsUserRoleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsUserRoleService {

	private PrtsUserRoleRepository prtsUserRoleRepository;

	@Autowired
	public PrtsUserRoleService(PrtsUserRoleRepository prtsUserRoleRepository) {
		this.prtsUserRoleRepository = prtsUserRoleRepository;
	}

}
