package com.hc.managers;

import com.hc.model.ProjectExperts;
import com.hc.model.PrtsProject;
import com.hc.repositories.PrtsProjectRepository;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectService {

	private PrtsProjectRepository prtsProjectRepository;

	@Autowired
	public PrtsProjectService(PrtsProjectRepository prtsProjectRepository) {
		this.prtsProjectRepository = prtsProjectRepository;
	}
	
	public PrtsProject AddNewProject(PrtsProject newPrj) {
		return prtsProjectRepository.save(newPrj);
		
	}
	
	public PrtsProject getProject(Long projectId) {
		return prtsProjectRepository.getById(projectId);
		
	}
	
	public List<ProjectExperts> getProjectExperts(Long projectId) {
		return prtsProjectRepository.FindProjectExperts(projectId);
		
	}
	public List<ProjectExperts> FindProjectExpertsOnly(Long projectId) {
		return prtsProjectRepository.FindProjectExpertsOnly(projectId);
		
	}
	
	

}
