package com.hc.managers;

import com.hc.model.PrtsRoleCode;
import com.hc.repositories.PrtsRoleCodeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsRoleCodeService {

	private PrtsRoleCodeRepository prtsRoleCodeRepository;

	@Autowired
	public PrtsRoleCodeService(PrtsRoleCodeRepository prtsRoleCodeRepository) {
		this.prtsRoleCodeRepository = prtsRoleCodeRepository;
	}

}
