package com.hc.managers;

import com.hc.model.PrtsProjectPerson;
import com.hc.repositories.PrtsProjectPersonRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectPersonService {

	private PrtsProjectPersonRepository prtsProjectPersonRepository;

	@Autowired
	public PrtsProjectPersonService(PrtsProjectPersonRepository prtsProjectPersonRepository) {
		this.prtsProjectPersonRepository = prtsProjectPersonRepository;
	}

}
