package com.hc.managers;

import com.hc.model.PrtsProjectTechnicalStudy;
import com.hc.repositories.PrtsProjectTechnicalStudyRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectTechnicalStudyService {

	private PrtsProjectTechnicalStudyRepository prtsProjectTechnicalStudyRepository;

	@Autowired
	public PrtsProjectTechnicalStudyService(PrtsProjectTechnicalStudyRepository prtsProjectTechnicalStudyRepository) {
		this.prtsProjectTechnicalStudyRepository = prtsProjectTechnicalStudyRepository;
	}

}
