package com.hc.managers;

import com.hc.model.PrtsProjectOfferingComponen;
import com.hc.repositories.PrtsProjectOfferingComponenRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectOfferingComponenService {

	private PrtsProjectOfferingComponenRepository prtsProjectOfferingComponenRepository;

	@Autowired
	public PrtsProjectOfferingComponenService(PrtsProjectOfferingComponenRepository prtsProjectOfferingComponenRepository) {
		this.prtsProjectOfferingComponenRepository = prtsProjectOfferingComponenRepository;
	}

}
