package com.hc.managers;

import com.hc.model.PrtsProjectTenderWriting;
import com.hc.repositories.PrtsProjectTenderWritingRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectTenderWritingService {

	private PrtsProjectTenderWritingRepository prtsProjectTenderWritingRepository;

	@Autowired
	public PrtsProjectTenderWritingService(PrtsProjectTenderWritingRepository prtsProjectTenderWritingRepository) {
		this.prtsProjectTenderWritingRepository = prtsProjectTenderWritingRepository;
	}

}
