package com.hc.managers;

import com.hc.model.PrtsProjectItemsPlanning;
import com.hc.repositories.PrtsProjectItemsPlanningRepository;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 02/07/2022
*/
@Component
public class PrtsProjectItemsPlanningService {

	private PrtsProjectItemsPlanningRepository prtsProjectItemsPlanningRepository;

	@Autowired
	public PrtsProjectItemsPlanningService(PrtsProjectItemsPlanningRepository prtsProjectItemsPlanningRepository) {
		this.prtsProjectItemsPlanningRepository = prtsProjectItemsPlanningRepository;
	}
	
	public void saveListOfItems(List<PrtsProjectItemsPlanning> allObjects) {
		prtsProjectItemsPlanningRepository.saveAll(allObjects);
		
	}

}
