package com.hc.managers;

import com.hc.model.PrtsProjectFinance;
import com.hc.repositories.PrtsProjectFinanceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectFinanceService {

	private PrtsProjectFinanceRepository prtsProjectFinanceRepository;

	@Autowired
	public PrtsProjectFinanceService(PrtsProjectFinanceRepository prtsProjectFinanceRepository) {
		this.prtsProjectFinanceRepository = prtsProjectFinanceRepository;
	}

}
