package com.hc.managers;

import com.hc.model.PrtsLookupType;
import com.hc.repositories.PrtsLookupTypeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 02/07/2022
*/
@Component
public class PrtsLookupTypeService {

	private PrtsLookupTypeRepository prtsLookupTypeRepository;

	@Autowired
	public PrtsLookupTypeService(PrtsLookupTypeRepository prtsLookupTypeRepository) {
		this.prtsLookupTypeRepository = prtsLookupTypeRepository;
	}

}
