package com.hc.managers;

import com.hc.model.PrtsProjectPurchase;
import com.hc.repositories.PrtsProjectPurchaseRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectPurchaseService {

	private PrtsProjectPurchaseRepository prtsProjectPurchaseRepository;

	@Autowired
	public PrtsProjectPurchaseService(PrtsProjectPurchaseRepository prtsProjectPurchaseRepository) {
		this.prtsProjectPurchaseRepository = prtsProjectPurchaseRepository;
	}

}
