package com.hc.managers;

import com.hc.model.PrtsProjectDocument;
import com.hc.repositories.PrtsProjectDocumentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectDocumentService {

	private PrtsProjectDocumentRepository prtsProjectDocumentRepository;

	@Autowired
	public PrtsProjectDocumentService(PrtsProjectDocumentRepository prtsProjectDocumentRepository) {
		this.prtsProjectDocumentRepository = prtsProjectDocumentRepository;
	}

}
