package com.hc.managers;

import com.hc.model.PrtsProjectProcedure;
import com.hc.repositories.PrtsProjectProcedureRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 25/01/2022
*/
@Component
public class PrtsProjectProcedureService {

	private PrtsProjectProcedureRepository prtsProjectProcedureRepository;

	@Autowired
	public PrtsProjectProcedureService(PrtsProjectProcedureRepository prtsProjectProcedureRepository) {
		this.prtsProjectProcedureRepository = prtsProjectProcedureRepository;
	}

}
